#!/bin/bash

[ ! -f /ccc/configs/phpstan.neon ] && { echo "Add phpstan configs!"; exit 2; }

if ! (/ccc/tools/phpstan/vendor/bin/phpstan --memory-limit=512M analyze -c /ccc/configs/phpstan.neon /app/src)
then
        echo "--------------"
        echo "PHPStan failed"
        echo "--------------"
        exit 1
fi

exit 0
